# zf250720.1447, zf250731.1701
# Sources:
# https://github.com/YanWenKun/ComfyUI-Docker/blob/main/cu129-slim/docker-compose.yml
# https://github.com/YanWenKun/ComfyUI-Docker/tree/main
# https://hub.docker.com/r/yanwk/comfyui-boot
# https://noted.lol/comfyui/

services:
  comfyui:
    init: true
    container_name: comfyui
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot:cu129-slim"
#    image: yanwk/comfyui-boot:cu129-megapak
    ports:
      - "8188:8188"
    volumes:
      - "./storage:/root"
      - "~/storage-models/models:/root/ComfyUI/models"
      - "~/storage-models/hf-hub:/root/.cache/huggingface/hub"
      - "~/storage-models/torch-hub:/root/.cache/torch/hub"
      - "./storage-user/input:/root/ComfyUI/input"
      - "./storage-user/output:/root/ComfyUI/output"
      - "./storage-user/workflows:/root/ComfyUI/user/default/workflows"
    environment:
        # Note: CLI_ARGS="--fast" for 40 series and newer GPUs.
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [all]
              capabilities: [gpu]

